blank_issues_enabled: true
contact_links:
  - name: dk documentation
    url: https://diskuv.com/dk/help/latest/
    about: Read the dk and dk0 documentation before filing, in case your question is already answered.
